// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use alsactl_sys;
use glib::object::Cast;
use glib::object::IsA;
use glib::signal::connect_raw;
use glib::signal::SignalHandlerId;
use glib::translate::*;
use glib::StaticType;
use glib::Value;
use glib_sys;
use gobject_sys;
use std::boxed::Box as Box_;
use std::fmt;
use std::mem::transmute;
use ElemInfoCommon;
use ElemInfoSingleArray;

glib_wrapper! {
    pub struct ElemInfoInteger64(Object<alsactl_sys::ALSACtlElemInfoInteger64, alsactl_sys::ALSACtlElemInfoInteger64Class, ElemInfoInteger64Class>) @implements ElemInfoCommon, ElemInfoSingleArray;

    match fn {
        get_type => || alsactl_sys::alsactl_elem_info_integer64_get_type(),
    }
}

impl ElemInfoInteger64 {
    pub fn new() -> ElemInfoInteger64 {
        unsafe { from_glib_full(alsactl_sys::alsactl_elem_info_integer64_new()) }
    }
}

impl Default for ElemInfoInteger64 {
    fn default() -> Self {
        Self::new()
    }
}

pub const NONE_ELEM_INFO_INTEGER64: Option<&ElemInfoInteger64> = None;

pub trait ElemInfoInteger64Ext: 'static {
    fn get_property_value_max(&self) -> i64;

    fn set_property_value_max(&self, value_max: i64);

    fn get_property_value_min(&self) -> i64;

    fn set_property_value_min(&self, value_min: i64);

    fn get_property_value_step(&self) -> i64;

    fn set_property_value_step(&self, value_step: i64);

    fn connect_property_value_max_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_property_value_min_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_property_value_step_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;
}

impl<O: IsA<ElemInfoInteger64>> ElemInfoInteger64Ext for O {
    fn get_property_value_max(&self) -> i64 {
        unsafe {
            let mut value = Value::from_type(<i64 as StaticType>::static_type());
            gobject_sys::g_object_get_property(
                self.to_glib_none().0 as *mut gobject_sys::GObject,
                b"value-max\0".as_ptr() as *const _,
                value.to_glib_none_mut().0,
            );
            value
                .get()
                .expect("Return Value for property `value-max` getter")
                .unwrap()
        }
    }

    fn set_property_value_max(&self, value_max: i64) {
        unsafe {
            gobject_sys::g_object_set_property(
                self.to_glib_none().0 as *mut gobject_sys::GObject,
                b"value-max\0".as_ptr() as *const _,
                Value::from(&value_max).to_glib_none().0,
            );
        }
    }

    fn get_property_value_min(&self) -> i64 {
        unsafe {
            let mut value = Value::from_type(<i64 as StaticType>::static_type());
            gobject_sys::g_object_get_property(
                self.to_glib_none().0 as *mut gobject_sys::GObject,
                b"value-min\0".as_ptr() as *const _,
                value.to_glib_none_mut().0,
            );
            value
                .get()
                .expect("Return Value for property `value-min` getter")
                .unwrap()
        }
    }

    fn set_property_value_min(&self, value_min: i64) {
        unsafe {
            gobject_sys::g_object_set_property(
                self.to_glib_none().0 as *mut gobject_sys::GObject,
                b"value-min\0".as_ptr() as *const _,
                Value::from(&value_min).to_glib_none().0,
            );
        }
    }

    fn get_property_value_step(&self) -> i64 {
        unsafe {
            let mut value = Value::from_type(<i64 as StaticType>::static_type());
            gobject_sys::g_object_get_property(
                self.to_glib_none().0 as *mut gobject_sys::GObject,
                b"value-step\0".as_ptr() as *const _,
                value.to_glib_none_mut().0,
            );
            value
                .get()
                .expect("Return Value for property `value-step` getter")
                .unwrap()
        }
    }

    fn set_property_value_step(&self, value_step: i64) {
        unsafe {
            gobject_sys::g_object_set_property(
                self.to_glib_none().0 as *mut gobject_sys::GObject,
                b"value-step\0".as_ptr() as *const _,
                Value::from(&value_step).to_glib_none().0,
            );
        }
    }

    fn connect_property_value_max_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_value_max_trampoline<P, F: Fn(&P) + 'static>(
            this: *mut alsactl_sys::ALSACtlElemInfoInteger64,
            _param_spec: glib_sys::gpointer,
            f: glib_sys::gpointer,
        ) where
            P: IsA<ElemInfoInteger64>,
        {
            let f: &F = &*(f as *const F);
            f(&ElemInfoInteger64::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::value-max\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_value_max_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    fn connect_property_value_min_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_value_min_trampoline<P, F: Fn(&P) + 'static>(
            this: *mut alsactl_sys::ALSACtlElemInfoInteger64,
            _param_spec: glib_sys::gpointer,
            f: glib_sys::gpointer,
        ) where
            P: IsA<ElemInfoInteger64>,
        {
            let f: &F = &*(f as *const F);
            f(&ElemInfoInteger64::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::value-min\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_value_min_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    fn connect_property_value_step_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_value_step_trampoline<P, F: Fn(&P) + 'static>(
            this: *mut alsactl_sys::ALSACtlElemInfoInteger64,
            _param_spec: glib_sys::gpointer,
            f: glib_sys::gpointer,
        ) where
            P: IsA<ElemInfoInteger64>,
        {
            let f: &F = &*(f as *const F);
            f(&ElemInfoInteger64::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::value-step\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_value_step_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }
}

impl fmt::Display for ElemInfoInteger64 {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "ElemInfoInteger64")
    }
}
