// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

mod device_info;
pub use self::device_info::DeviceInfo;

mod device_params;
pub use self::device_params::DeviceParams;

mod device_status;
pub use self::device_status::DeviceStatus;

mod instance_info;
pub use self::instance_info::InstanceInfo;

mod instance_params;
pub use self::instance_params::InstanceParams;

mod instance_status;
pub use self::instance_status::InstanceStatus;

mod user_instance;
pub use self::user_instance::UserInstance;

mod device_id;
pub use self::device_id::DeviceId;

mod real_time_event;
pub use self::real_time_event::RealTimeEvent;

mod tick_time_event;
pub use self::tick_time_event::TickTimeEvent;

mod enums;
pub use self::enums::Class;
pub use self::enums::EventType;
pub use self::enums::RealTimeEventType;
pub use self::enums::SlaveClass;
pub use self::enums::SpecificGlobalDevice;
pub use self::enums::UserInstanceError;

mod flags;
pub use self::flags::DeviceInfoFlag;
pub use self::flags::InstanceParamFlag;

/// Functions callable without instantiation.
pub mod functions;

#[doc(hidden)]
pub mod traits {
    pub use super::device_info::DeviceInfoExt;
    pub use super::device_params::DeviceParamsExt;
    pub use super::device_status::DeviceStatusExt;
    pub use super::instance_info::InstanceInfoExt;
    pub use super::instance_params::InstanceParamsExt;
    pub use super::instance_status::InstanceStatusExt;
    pub use super::user_instance::UserInstanceExt;
}
