// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use glib::translate::*;
use std::mem;

glib::wrapper! {
    #[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct TickTimeEvent(Boxed<ffi::ALSATimerTickTimeEvent>);

    match fn {
        copy => |ptr| glib::gobject_ffi::g_boxed_copy(ffi::alsatimer_tick_time_event_get_type(), ptr as *mut _) as *mut ffi::ALSATimerTickTimeEvent,
        free => |ptr| glib::gobject_ffi::g_boxed_free(ffi::alsatimer_tick_time_event_get_type(), ptr as *mut _),
        type_ => || ffi::alsatimer_tick_time_event_get_type(),
    }
}

impl TickTimeEvent {
    #[doc(alias = "alsatimer_tick_time_event_get_count")]
    #[doc(alias = "get_count")]
    pub fn count(&self) -> u32 {
        unsafe {
            let mut count = mem::MaybeUninit::uninit();
            ffi::alsatimer_tick_time_event_get_count(self.to_glib_none().0, count.as_mut_ptr());
            let count = count.assume_init();
            count
        }
    }

    #[doc(alias = "alsatimer_tick_time_event_get_resolution")]
    #[doc(alias = "get_resolution")]
    pub fn resolution(&self) -> u32 {
        unsafe {
            let mut resolution = mem::MaybeUninit::uninit();
            ffi::alsatimer_tick_time_event_get_resolution(
                self.to_glib_none().0,
                resolution.as_mut_ptr(),
            );
            let resolution = resolution.assume_init();
            resolution
        }
    }
}

unsafe impl Send for TickTimeEvent {}
