[package]
edition = "2018"
name = "alsatimer"
version = "0.3.0"
# For publishing.
authors = ["Takashi Sakamoto <o-takashi@sakamocchi.jp>"]
description = "API binding for libalsatimer library"
license = "MIT"
repository = "https://github.com/alsa-project/alsa-gobject-rs"

[lib]
name = "alsatimer"

[dependencies]
libc = "0.2"
bitflags = "1.0"
glib = "0.15"
ffi = {package= "alsatimer-sys", path = "../alsatimer-sys", version = "0.3" }

[dev-dependencies]
gir-format-check = "^0.1"
