// This file was generated by gir (https://github.com/gtk-rs/gir)
// from 
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "ALSASeqClientInfo", sizeof(ALSASeqClientInfo), alignof(ALSASeqClientInfo));
    printf("%s;%zu;%zu\n", "ALSASeqClientInfoClass", sizeof(ALSASeqClientInfoClass), alignof(ALSASeqClientInfoClass));
    printf("%s;%zu;%zu\n", "ALSASeqClientPool", sizeof(ALSASeqClientPool), alignof(ALSASeqClientPool));
    printf("%s;%zu;%zu\n", "ALSASeqClientPoolClass", sizeof(ALSASeqClientPoolClass), alignof(ALSASeqClientPoolClass));
    printf("%s;%zu;%zu\n", "ALSASeqClientType", sizeof(ALSASeqClientType), alignof(ALSASeqClientType));
    printf("%s;%zu;%zu\n", "ALSASeqEventCntr", sizeof(ALSASeqEventCntr), alignof(ALSASeqEventCntr));
    printf("%s;%zu;%zu\n", "ALSASeqEventError", sizeof(ALSASeqEventError), alignof(ALSASeqEventError));
    printf("%s;%zu;%zu\n", "ALSASeqEventLengthMode", sizeof(ALSASeqEventLengthMode), alignof(ALSASeqEventLengthMode));
    printf("%s;%zu;%zu\n", "ALSASeqEventPriorityMode", sizeof(ALSASeqEventPriorityMode), alignof(ALSASeqEventPriorityMode));
    printf("%s;%zu;%zu\n", "ALSASeqEventTimeMode", sizeof(ALSASeqEventTimeMode), alignof(ALSASeqEventTimeMode));
    printf("%s;%zu;%zu\n", "ALSASeqEventTstampMode", sizeof(ALSASeqEventTstampMode), alignof(ALSASeqEventTstampMode));
    printf("%s;%zu;%zu\n", "ALSASeqEventType", sizeof(ALSASeqEventType), alignof(ALSASeqEventType));
    printf("%s;%zu;%zu\n", "ALSASeqFilterAttrFlag", sizeof(ALSASeqFilterAttrFlag), alignof(ALSASeqFilterAttrFlag));
    printf("%s;%zu;%zu\n", "ALSASeqPortAttrFlag", sizeof(ALSASeqPortAttrFlag), alignof(ALSASeqPortAttrFlag));
    printf("%s;%zu;%zu\n", "ALSASeqPortCapFlag", sizeof(ALSASeqPortCapFlag), alignof(ALSASeqPortCapFlag));
    printf("%s;%zu;%zu\n", "ALSASeqPortInfo", sizeof(ALSASeqPortInfo), alignof(ALSASeqPortInfo));
    printf("%s;%zu;%zu\n", "ALSASeqPortInfoClass", sizeof(ALSASeqPortInfoClass), alignof(ALSASeqPortInfoClass));
    printf("%s;%zu;%zu\n", "ALSASeqQuerySubscribeType", sizeof(ALSASeqQuerySubscribeType), alignof(ALSASeqQuerySubscribeType));
    printf("%s;%zu;%zu\n", "ALSASeqQueueInfo", sizeof(ALSASeqQueueInfo), alignof(ALSASeqQueueInfo));
    printf("%s;%zu;%zu\n", "ALSASeqQueueInfoClass", sizeof(ALSASeqQueueInfoClass), alignof(ALSASeqQueueInfoClass));
    printf("%s;%zu;%zu\n", "ALSASeqQueueStatus", sizeof(ALSASeqQueueStatus), alignof(ALSASeqQueueStatus));
    printf("%s;%zu;%zu\n", "ALSASeqQueueStatusClass", sizeof(ALSASeqQueueStatusClass), alignof(ALSASeqQueueStatusClass));
    printf("%s;%zu;%zu\n", "ALSASeqQueueTempo", sizeof(ALSASeqQueueTempo), alignof(ALSASeqQueueTempo));
    printf("%s;%zu;%zu\n", "ALSASeqQueueTempoClass", sizeof(ALSASeqQueueTempoClass), alignof(ALSASeqQueueTempoClass));
    printf("%s;%zu;%zu\n", "ALSASeqQueueTimerAlsa", sizeof(ALSASeqQueueTimerAlsa), alignof(ALSASeqQueueTimerAlsa));
    printf("%s;%zu;%zu\n", "ALSASeqQueueTimerAlsaClass", sizeof(ALSASeqQueueTimerAlsaClass), alignof(ALSASeqQueueTimerAlsaClass));
    printf("%s;%zu;%zu\n", "ALSASeqQueueTimerCommonInterface", sizeof(ALSASeqQueueTimerCommonInterface), alignof(ALSASeqQueueTimerCommonInterface));
    printf("%s;%zu;%zu\n", "ALSASeqQueueTimerType", sizeof(ALSASeqQueueTimerType), alignof(ALSASeqQueueTimerType));
    printf("%s;%zu;%zu\n", "ALSASeqRemoveFilter", sizeof(ALSASeqRemoveFilter), alignof(ALSASeqRemoveFilter));
    printf("%s;%zu;%zu\n", "ALSASeqRemoveFilterClass", sizeof(ALSASeqRemoveFilterClass), alignof(ALSASeqRemoveFilterClass));
    printf("%s;%zu;%zu\n", "ALSASeqRemoveFilterFlag", sizeof(ALSASeqRemoveFilterFlag), alignof(ALSASeqRemoveFilterFlag));
    printf("%s;%zu;%zu\n", "ALSASeqSpecificAddress", sizeof(ALSASeqSpecificAddress), alignof(ALSASeqSpecificAddress));
    printf("%s;%zu;%zu\n", "ALSASeqSpecificClientId", sizeof(ALSASeqSpecificClientId), alignof(ALSASeqSpecificClientId));
    printf("%s;%zu;%zu\n", "ALSASeqSpecificPortId", sizeof(ALSASeqSpecificPortId), alignof(ALSASeqSpecificPortId));
    printf("%s;%zu;%zu\n", "ALSASeqSpecificQueueId", sizeof(ALSASeqSpecificQueueId), alignof(ALSASeqSpecificQueueId));
    printf("%s;%zu;%zu\n", "ALSASeqSubscribeData", sizeof(ALSASeqSubscribeData), alignof(ALSASeqSubscribeData));
    printf("%s;%zu;%zu\n", "ALSASeqSubscribeDataClass", sizeof(ALSASeqSubscribeDataClass), alignof(ALSASeqSubscribeDataClass));
    printf("%s;%zu;%zu\n", "ALSASeqSystemInfo", sizeof(ALSASeqSystemInfo), alignof(ALSASeqSystemInfo));
    printf("%s;%zu;%zu\n", "ALSASeqSystemInfoClass", sizeof(ALSASeqSystemInfoClass), alignof(ALSASeqSystemInfoClass));
    printf("%s;%zu;%zu\n", "ALSASeqUserClient", sizeof(ALSASeqUserClient), alignof(ALSASeqUserClient));
    printf("%s;%zu;%zu\n", "ALSASeqUserClientClass", sizeof(ALSASeqUserClientClass), alignof(ALSASeqUserClientClass));
    printf("%s;%zu;%zu\n", "ALSASeqUserClientError", sizeof(ALSASeqUserClientError), alignof(ALSASeqUserClientError));
    return 0;
}
