[options]
work_mode = "sys"
library = "ALSAHwdep"
version = "0.0"
min_cfg_version = "0.2"
single_version_file = "."
external_libraries = [
  "GLib",
  "GObject",
]

[crate_name_overrides]
"alsa_hwdep" = "alsahwdep"

