[package]
name = "alsaseq-sys"
version = "0.0.1"
links = "alsaseq"
build = "build.rs"
description = "FFI binding for libalsaseq library"
license = "MIT"
repository = "https://github.com/alsa-project/alsa-gobject-rs"

[package.metadata.docs.rs]
features = ["dox"]

[lib]
name = "alsaseq_sys"

[dependencies]
libc = "0.2"

glib-sys = "0.10"
gobject-sys = "0.10"

alsatimer-sys = { path = "../alsatimer-sys", version = "0.0"}

[build-dependencies]
pkg-config = "0.3.7"

[dev-dependencies]
shell-words = "0.1.0"
tempfile = "3"

[features]
dox = []
