[package]
name = "alsaseq-sys"
version = "0.0.1"
links = "alsaseq"
build = "build.rs"
[package.metadata.docs.rs]
features = ["dox"]

[lib]
name = "alsaseq_sys"

[dependencies]
libc = "0.2"

glib-sys = "0.10"
gobject-sys = "0.10"

[dependencies.alsatimer-sys]
path = "../alsatimer-sys"

[build-dependencies]
pkg-config = "0.3.7"

[dev-dependencies]
shell-words = "0.1.0"
tempfile = "3"

[features]
dox = []
