[package]
name = "alsaseq-sys"
version = "0.2.0"
links = "alsaseq"
build = "build.rs"
description = "FFI binding for libalsaseq library"
license = "MIT"
repository = "https://github.com/alsa-project/alsa-gobject-rs"
[package.metadata.docs.rs]
features = ["dox"]
[package.metadata.system-deps.alsaseq]
name = "alsaseq"
version = "0.2"

[package.metadata.system-deps.alsaseq.feature-versions]

[lib]
name = "alsaseq_sys"

[dependencies]
libc = "0.2"
glib-sys = "0.10"
gobject-sys = "0.10"

[dependencies.alsatimer-sys]
path = "../alsatimer-sys"
version = "0.2"

[build-dependencies]
pkg-config = "0.3.7"
system-deps = "1.3"

[dev-dependencies]
shell-words = "0.1.0"
tempfile = "3"

[features]
dox = []
