[options]
work_mode = "sys"
library = "ALSASeq"
version = "0.0"
min_cfg_version = "0.3"
single_version_file = "."
external_libraries = [
   "GLib",
   "GObject",
   "ALSATimer",
]

[crate_name_overrides]
"alsa_seq" = "alsaseq"
"alsa_timer" = "alsatimer"
