// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use alsarawmidi_sys;
use glib::translate::*;
use glib::value::FromValue;
use glib::value::FromValueOptional;
use glib::value::SetValue;
use glib::value::Value;
use glib::StaticType;
use glib::Type;
use gobject_sys;

bitflags! {
    pub struct StreamPairInfoFlag: u32 {
        const OUTPUT = 1;
        const INPUT = 2;
        const DUPLEX = 4;
    }
}

#[doc(hidden)]
impl ToGlib for StreamPairInfoFlag {
    type GlibType = alsarawmidi_sys::ALSARawmidiStreamPairInfoFlag;

    fn to_glib(&self) -> alsarawmidi_sys::ALSARawmidiStreamPairInfoFlag {
        self.bits()
    }
}

#[doc(hidden)]
impl FromGlib<alsarawmidi_sys::ALSARawmidiStreamPairInfoFlag> for StreamPairInfoFlag {
    fn from_glib(value: alsarawmidi_sys::ALSARawmidiStreamPairInfoFlag) -> StreamPairInfoFlag {
        StreamPairInfoFlag::from_bits_truncate(value)
    }
}

impl StaticType for StreamPairInfoFlag {
    fn static_type() -> Type {
        unsafe { from_glib(alsarawmidi_sys::alsarawmidi_stream_pair_info_flag_get_type()) }
    }
}

impl<'a> FromValueOptional<'a> for StreamPairInfoFlag {
    unsafe fn from_value_optional(value: &Value) -> Option<Self> {
        Some(FromValue::from_value(value))
    }
}

impl<'a> FromValue<'a> for StreamPairInfoFlag {
    unsafe fn from_value(value: &Value) -> Self {
        from_glib(gobject_sys::g_value_get_flags(value.to_glib_none().0))
    }
}

impl SetValue for StreamPairInfoFlag {
    unsafe fn set_value(value: &mut Value, this: &Self) {
        gobject_sys::g_value_set_flags(value.to_glib_none_mut().0, this.to_glib())
    }
}
