// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use bitflags::bitflags;
use glib::translate::*;
use glib::value::FromValue;
use glib::value::ToValue;
use glib::StaticType;
use glib::Type;
use std::fmt;

bitflags! {
    #[doc(alias = "ALSARawmidiStreamPairInfoFlag")]
    pub struct StreamPairInfoFlag: u32 {
        #[doc(alias = "ALSARAWMIDI_STREAM_PAIR_INFO_FLAG_OUTPUT")]
        const OUTPUT = ffi::ALSARAWMIDI_STREAM_PAIR_INFO_FLAG_OUTPUT as u32;
        #[doc(alias = "ALSARAWMIDI_STREAM_PAIR_INFO_FLAG_INPUT")]
        const INPUT = ffi::ALSARAWMIDI_STREAM_PAIR_INFO_FLAG_INPUT as u32;
        #[doc(alias = "ALSARAWMIDI_STREAM_PAIR_INFO_FLAG_DUPLEX")]
        const DUPLEX = ffi::ALSARAWMIDI_STREAM_PAIR_INFO_FLAG_DUPLEX as u32;
    }
}

impl fmt::Display for StreamPairInfoFlag {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        <Self as fmt::Debug>::fmt(self, f)
    }
}

#[doc(hidden)]
impl IntoGlib for StreamPairInfoFlag {
    type GlibType = ffi::ALSARawmidiStreamPairInfoFlag;

    fn into_glib(self) -> ffi::ALSARawmidiStreamPairInfoFlag {
        self.bits()
    }
}

#[doc(hidden)]
impl FromGlib<ffi::ALSARawmidiStreamPairInfoFlag> for StreamPairInfoFlag {
    unsafe fn from_glib(value: ffi::ALSARawmidiStreamPairInfoFlag) -> Self {
        Self::from_bits_truncate(value)
    }
}

impl StaticType for StreamPairInfoFlag {
    fn static_type() -> Type {
        unsafe { from_glib(ffi::alsarawmidi_stream_pair_info_flag_get_type()) }
    }
}

impl glib::value::ValueType for StreamPairInfoFlag {
    type Type = Self;
}

unsafe impl<'a> FromValue<'a> for StreamPairInfoFlag {
    type Checker = glib::value::GenericValueTypeChecker<Self>;

    unsafe fn from_value(value: &'a glib::Value) -> Self {
        from_glib(glib::gobject_ffi::g_value_get_flags(value.to_glib_none().0))
    }
}

impl ToValue for StreamPairInfoFlag {
    fn to_value(&self) -> glib::Value {
        let mut value = glib::Value::for_value_type::<Self>();
        unsafe {
            glib::gobject_ffi::g_value_set_flags(value.to_glib_none_mut().0, self.into_glib());
        }
        value
    }

    fn value_type(&self) -> glib::Type {
        Self::static_type()
    }
}
