// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

mod stream_pair;
pub use self::stream_pair::StreamPair;

mod substream_info;
pub use self::substream_info::SubstreamInfo;

mod substream_params;
pub use self::substream_params::SubstreamParams;

mod substream_status;
pub use self::substream_status::SubstreamStatus;

mod enums;
pub use self::enums::StreamDirection;
pub use self::enums::StreamPairError;

mod flags;
pub use self::flags::StreamPairInfoFlag;

/// For functions available globally.
pub mod functions;

#[doc(hidden)]
pub mod traits {
    pub use super::stream_pair::StreamPairExt;
    pub use super::substream_info::SubstreamInfoExt;
    pub use super::substream_params::SubstreamParamsExt;
    pub use super::substream_status::SubstreamStatusExt;
}
