// This file was generated by gir (https://github.com/gtk-rs/gir)
// from 
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "ALSAHwdepDeviceInfo", sizeof(ALSAHwdepDeviceInfo), alignof(ALSAHwdepDeviceInfo));
    printf("%s;%zu;%zu\n", "ALSAHwdepDeviceInfoClass", sizeof(ALSAHwdepDeviceInfoClass), alignof(ALSAHwdepDeviceInfoClass));
    printf("%s;%zu;%zu\n", "ALSAHwdepIfaceType", sizeof(ALSAHwdepIfaceType), alignof(ALSAHwdepIfaceType));
    return 0;
}
