// This file was generated by gir (https://github.com/gtk-rs/gir)
// from 
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "ALSACtlCard", sizeof(ALSACtlCard), alignof(ALSACtlCard));
    printf("%s;%zu;%zu\n", "ALSACtlCardClass", sizeof(ALSACtlCardClass), alignof(ALSACtlCardClass));
    printf("%s;%zu;%zu\n", "ALSACtlCardError", sizeof(ALSACtlCardError), alignof(ALSACtlCardError));
    printf("%s;%zu;%zu\n", "ALSACtlCardInfo", sizeof(ALSACtlCardInfo), alignof(ALSACtlCardInfo));
    printf("%s;%zu;%zu\n", "ALSACtlCardInfoClass", sizeof(ALSACtlCardInfoClass), alignof(ALSACtlCardInfoClass));
    printf("%s;%zu;%zu\n", "ALSACtlElemAccessFlag", sizeof(ALSACtlElemAccessFlag), alignof(ALSACtlElemAccessFlag));
    printf("%s;%zu;%zu\n", "ALSACtlElemEventMask", sizeof(ALSACtlElemEventMask), alignof(ALSACtlElemEventMask));
    printf("%s;%zu;%zu\n", "ALSACtlElemIfaceType", sizeof(ALSACtlElemIfaceType), alignof(ALSACtlElemIfaceType));
    printf("%s;%zu;%zu\n", "ALSACtlElemInfo", sizeof(ALSACtlElemInfo), alignof(ALSACtlElemInfo));
    printf("%s;%zu;%zu\n", "ALSACtlElemInfoClass", sizeof(ALSACtlElemInfoClass), alignof(ALSACtlElemInfoClass));
    printf("%s;%zu;%zu\n", "ALSACtlElemType", sizeof(ALSACtlElemType), alignof(ALSACtlElemType));
    printf("%s;%zu;%zu\n", "ALSACtlElemValue", sizeof(ALSACtlElemValue), alignof(ALSACtlElemValue));
    printf("%s;%zu;%zu\n", "ALSACtlElemValueClass", sizeof(ALSACtlElemValueClass), alignof(ALSACtlElemValueClass));
    printf("%s;%zu;%zu\n", "ALSACtlEventType", sizeof(ALSACtlEventType), alignof(ALSACtlEventType));
    return 0;
}
