[package]
name = "alsarawmidi"
version = "0.1.1"
authors = ["Takashi Sakamoto <o-takashi@sakamocchi.jp>"]
description = "API binding for libalsarawmidi library"
license = "MIT"
repository = "https://github.com/alsa-project/alsa-gobject-rs"

[lib]
name = "alsarawmidi"

[dependencies]
libc = "0.2"
bitflags = "1.0"

glib = "0.10"
glib-sys = "0.10"
gobject-sys = "0.10"

alsarawmidi-sys = { path = "../alsarawmidi-sys", version = "0.1" }

[dev-dependencies]
gir-format-check = "^0.1"
