[package]
name = "alsaseq"
version = "0.2.0"
authors = ["Takashi Sakamoto <o-takashi@sakamocchi.jp>"]
description = "API binding for libalsaseq library"
license = "MIT"
repository = "https://github.com/alsa-project/alsa-gobject-rs"

[lib]
name = "alsaseq"

[dependencies]
libc = "0.2"
bitflags = "1.0"

glib = "0.10"
glib-sys = "0.10"
gobject-sys = "0.10"

alsatimer-sys = { path = "../alsatimer-sys", version = "0.2" }
alsaseq-sys = { path = "../alsaseq-sys", version = "0.2" }
alsatimer = { path = "../alsatimer", version = "0.2" }

[dev-dependencies]
gir-format-check = "^0.1"
