[crate_name_overrides]
"alsa_seq" = "alsaseq"
"alsa_timer" = "alsatimer"

[options]
girs_directories = ["../gir-files", ".."]
work_mode = "normal"
library = "ALSASeq"
version = "0.0"
min_cfg_version = "0.3"
single_version_file = true

manual = [
    "GLib.Error",
    "GLib.Source",
    "ALSATimer.DeviceId",
]

generate = [
    "ALSASeq.SpecificAddress",
    "ALSASeq.SpecificClientId",
    "ALSASeq.ClientType",
    "ALSASeq.FilterAttrFlag",
    "ALSASeq.SpecificPortId",
    "ALSASeq.PortCapFlag",
    "ALSASeq.PortAttrFlag",
    "ALSASeq.EventError",
    "ALSASeq.EventType",
    "ALSASeq.EventTstampMode",
    "ALSASeq.EventTimeMode",
    "ALSASeq.EventLengthMode",
    "ALSASeq.EventPriorityMode",
    "ALSASeq.SpecificQueueId",
    "ALSASeq.QuerySubscribeType",
    "ALSASeq.QueueTimerType",
    "ALSASeq.RemoveFilterFlag",
    "ALSASeq.SystemInfo",
    "ALSASeq.PortInfo",
    "ALSASeq.ClientPool",
    "ALSASeq.SubscribeData",
    "ALSASeq.QueueInfo",
    "ALSASeq.UserClientError",
    "ALSASeq.QueueTimerCommon",
    "ALSASeq.QueueTimerAlsa",
]

[[object]]
name = "ALSASeq.*"
status = "generate"
    [[object.function]]
    name = "get_queue_status"
    manual = true
    [[object.function]]
    name = "get_subscription_list"
    manual = true

[[object]]
name = "ALSASeq.UserClient"
status = "generate"
manual_traits = ["UserClientExtManual"]
    [[object.function]]
    name = "get_protocol_version"
    manual = true
    [[object.function]]
    name = "create_port"
    manual = true
    [[object.function]]
    name = "create_port_at"
    manual = true
    [[object.function]]
    name = "create_queue"
    manual = true
    [[object.function]]
    name = "get_info"
    manual = true
    [[object.function]]
    name = "get_pool"
    manual = true
    [[object.function]]
    name = "set_queue_timer"
    manual = true
    [[object.function]]
    name = "get_queue_timer"
    manual = true
    [[object.function]]
    name = "schedule_events"
    manual = true


[[object]]
name = "ALSASeq.EventDataConnect"
status = "generate"
concurrency = "send"
    [[object.function]]
    name = "get_src"
    manual = true
    [[object.function]]
    name = "get_dst"
    manual = true

[[object]]
name = "ALSASeq.Addr"
status = "generate"
concurrency = "send"

[[object]]
name = "ALSASeq.EventDataCtl"
status = "generate"
concurrency = "send"

[[object]]
name = "ALSASeq.EventDataNote"
status = "generate"
concurrency = "send"

[[object]]
name = "ALSASeq.EventDataQueue"
status = "generate"
concurrency = "send"
    [[object.function]]
    name = "get_byte_param"
    manual = true
    [[object.function]]
    name = "set_byte_param"
    manual = true
    [[object.function]]
    name = "set_skew_param"
    manual = true
    [[object.function]]
    name = "get_skew_param"
    manual = true
    [[object.function]]
    name = "get_quadlet_param"
    manual = true
    [[object.function]]
    name = "set_quadlet_param"
    manual = true
    [[object.function]]
    name = "get_real_time_param"
    manual = true
    [[object.function]]
    name = "set_real_time_param"
    manual = true

[[object]]
name = "ALSASeq.EventDataResult"
status = "generate"
concurrency = "send"

[[object]]
name = "ALSASeq.ClientInfo"
status = "generate"
manual_traits = ["ClientInfoExtManual"]
    [[object.function]]
    name = "get_event_filter"
    manual = true
    [[object.function]]
    name = "set_event_filter"
    manual = true

[[object]]
name = "ALSASeq.QueueStatus"
status = "generate"
manual_traits = ["QueueStatusExtManual"]
    [[object.function]]
    name = "get_real_time"
    manual = true

[[object]]
name = "ALSASeq.QueueTempo"
status = "generate"
manual_traits = ["QueueTempoExtManual"]
    [[object.function]]
    name = "get_skew"
    manual = true
    [[object.function]]
    name = "set_skew"
    manual = true

[[object]]
name = "ALSASeq.RemoveFilter"
status = "generate"
manual_traits = ["RemoveFilterExtManual"]
concurrency = "send"
    [[object.function]]
    name = "get_real_time"
    manual = true
    [[object.function]]
    name = "set_real_time"
    manual = true
    [[object.property]]
    name = "tag"
    manual = true

[[object]]
name = "ALSASeq.Event"
status = "generate"
concurrency = "send"
    [[object.function]]
    name = "get_addr_data"
    manual = true
    [[object.function]]
    name = "get_blob_data"
    manual = true
    [[object.function]]
    name = "get_byte_data"
    manual = true
    [[object.function]]
    name = "get_connect_data"
    manual = true
    [[object.function]]
    name = "get_ctl_data"
    manual = true
    [[object.function]]
    name = "get_destination"
    manual = true
    [[object.function]]
    name = "get_note_data"
    manual = true
    [[object.function]]
    name = "get_pointer_data"
    manual = true
    [[object.function]]
    name = "get_quadlet_data"
    manual = true
    [[object.function]]
    name = "get_queue_data"
    manual = true
    [[object.function]]
    name = "get_real_time"
    manual = true
    [[object.function]]
    name = "get_real_time_data"
    manual = true
    [[object.function]]
    name = "get_result_data"
    manual = true
    [[object.function]]
    name = "get_source"
    manual = true
    [[object.function]]
    name = "get_tick_time"
    manual = true
    [[object.function]]
    name = "get_tick_time_data"
    manual = true
    [[object.function]]
    name = "set_byte_data"
    manual = true
    [[object.function]]
    name = "set_pointer_data"
    manual = true
    [[object.function]]
    name = "set_quadlet_data"
    manual = true
    [[object.function]]
    name = "set_real_time"
    manual = true
    [[object.function]]
    name = "set_real_time_data"
    manual = true

[[object]]
name = "ALSASeq.EventCntr"
status = "generate"
concurrency = "send"
    [[object.function]]
    name = "deserialize"
    manual = true
