[package]
name = "alsactl"
version = "0.0.0"
authors = ["Takashi Sakamoto <o-takashi@sakamocchi.jp>"]

[lib]
name = "alsactl"

[dependencies]
libc = "0.2"
bitflags = "1.0"

glib = "0.10"
glib-sys = "0.10"
gobject-sys = "0.10"

alsactl-sys = {path = "../alsactl-sys", version = "0.0" }

[dev-dependencies]
gir-format-check = "^0.1"
