// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use crate::ClientType;
use crate::FilterAttrFlag;
use glib::object::Cast;
use glib::object::IsA;
use glib::signal::connect_raw;
use glib::signal::SignalHandlerId;
use glib::translate::*;
use std::boxed::Box as Box_;
use std::fmt;
use std::mem::transmute;

glib::wrapper! {
    #[doc(alias = "ALSASeqClientInfo")]
    pub struct ClientInfo(Object<ffi::ALSASeqClientInfo, ffi::ALSASeqClientInfoClass>);

    match fn {
        type_ => || ffi::alsaseq_client_info_get_type(),
    }
}

impl ClientInfo {
    pub const NONE: Option<&'static ClientInfo> = None;

    #[doc(alias = "alsaseq_client_info_new")]
    pub fn new() -> ClientInfo {
        unsafe { from_glib_full(ffi::alsaseq_client_info_new()) }
    }
}

impl Default for ClientInfo {
    fn default() -> Self {
        Self::new()
    }
}

pub trait ClientInfoExt: 'static {
    #[doc(alias = "card-id")]
    fn card_id(&self) -> i32;

    #[doc(alias = "card-id")]
    fn set_card_id(&self, card_id: i32);

    #[doc(alias = "client-id")]
    fn client_id(&self) -> u8;

    #[doc(alias = "client-id")]
    fn set_client_id(&self, client_id: u8);

    #[doc(alias = "filter-attributes")]
    fn filter_attributes(&self) -> FilterAttrFlag;

    #[doc(alias = "filter-attributes")]
    fn set_filter_attributes(&self, filter_attributes: FilterAttrFlag);

    #[doc(alias = "lost-count")]
    fn lost_count(&self) -> i32;

    fn name(&self) -> Option<glib::GString>;

    fn set_name(&self, name: Option<&str>);

    #[doc(alias = "port-count")]
    fn port_count(&self) -> i32;

    #[doc(alias = "process-id")]
    fn process_id(&self) -> i64;

    #[doc(alias = "type")]
    fn type_(&self) -> ClientType;

    #[doc(alias = "type")]
    fn set_type(&self, type_: ClientType);

    #[doc(alias = "use-filter")]
    fn uses_filter(&self) -> bool;

    #[doc(alias = "use-filter")]
    fn set_use_filter(&self, use_filter: bool);

    #[doc(alias = "card-id")]
    fn connect_card_id_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    #[doc(alias = "client-id")]
    fn connect_client_id_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    #[doc(alias = "filter-attributes")]
    fn connect_filter_attributes_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    #[doc(alias = "lost-count")]
    fn connect_lost_count_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    #[doc(alias = "name")]
    fn connect_name_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    #[doc(alias = "port-count")]
    fn connect_port_count_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    #[doc(alias = "process-id")]
    fn connect_process_id_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    #[doc(alias = "type")]
    fn connect_type_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    #[doc(alias = "use-filter")]
    fn connect_use_filter_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;
}

impl<O: IsA<ClientInfo>> ClientInfoExt for O {
    fn card_id(&self) -> i32 {
        glib::ObjectExt::property(self.as_ref(), "card-id")
    }

    fn set_card_id(&self, card_id: i32) {
        glib::ObjectExt::set_property(self.as_ref(), "card-id", &card_id)
    }

    fn client_id(&self) -> u8 {
        glib::ObjectExt::property(self.as_ref(), "client-id")
    }

    fn set_client_id(&self, client_id: u8) {
        glib::ObjectExt::set_property(self.as_ref(), "client-id", &client_id)
    }

    fn filter_attributes(&self) -> FilterAttrFlag {
        glib::ObjectExt::property(self.as_ref(), "filter-attributes")
    }

    fn set_filter_attributes(&self, filter_attributes: FilterAttrFlag) {
        glib::ObjectExt::set_property(self.as_ref(), "filter-attributes", &filter_attributes)
    }

    fn lost_count(&self) -> i32 {
        glib::ObjectExt::property(self.as_ref(), "lost-count")
    }

    fn name(&self) -> Option<glib::GString> {
        glib::ObjectExt::property(self.as_ref(), "name")
    }

    fn set_name(&self, name: Option<&str>) {
        glib::ObjectExt::set_property(self.as_ref(), "name", &name)
    }

    fn port_count(&self) -> i32 {
        glib::ObjectExt::property(self.as_ref(), "port-count")
    }

    fn process_id(&self) -> i64 {
        glib::ObjectExt::property(self.as_ref(), "process-id")
    }

    fn type_(&self) -> ClientType {
        glib::ObjectExt::property(self.as_ref(), "type")
    }

    fn set_type(&self, type_: ClientType) {
        glib::ObjectExt::set_property(self.as_ref(), "type", &type_)
    }

    fn uses_filter(&self) -> bool {
        glib::ObjectExt::property(self.as_ref(), "use-filter")
    }

    fn set_use_filter(&self, use_filter: bool) {
        glib::ObjectExt::set_property(self.as_ref(), "use-filter", &use_filter)
    }

    fn connect_card_id_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_card_id_trampoline<P: IsA<ClientInfo>, F: Fn(&P) + 'static>(
            this: *mut ffi::ALSASeqClientInfo,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(ClientInfo::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::card-id\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_card_id_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    fn connect_client_id_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_client_id_trampoline<
            P: IsA<ClientInfo>,
            F: Fn(&P) + 'static,
        >(
            this: *mut ffi::ALSASeqClientInfo,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(ClientInfo::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::client-id\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_client_id_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    fn connect_filter_attributes_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_filter_attributes_trampoline<
            P: IsA<ClientInfo>,
            F: Fn(&P) + 'static,
        >(
            this: *mut ffi::ALSASeqClientInfo,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(ClientInfo::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::filter-attributes\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_filter_attributes_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    fn connect_lost_count_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_lost_count_trampoline<
            P: IsA<ClientInfo>,
            F: Fn(&P) + 'static,
        >(
            this: *mut ffi::ALSASeqClientInfo,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(ClientInfo::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::lost-count\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_lost_count_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    fn connect_name_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_name_trampoline<P: IsA<ClientInfo>, F: Fn(&P) + 'static>(
            this: *mut ffi::ALSASeqClientInfo,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(ClientInfo::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::name\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_name_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    fn connect_port_count_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_port_count_trampoline<
            P: IsA<ClientInfo>,
            F: Fn(&P) + 'static,
        >(
            this: *mut ffi::ALSASeqClientInfo,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(ClientInfo::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::port-count\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_port_count_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    fn connect_process_id_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_process_id_trampoline<
            P: IsA<ClientInfo>,
            F: Fn(&P) + 'static,
        >(
            this: *mut ffi::ALSASeqClientInfo,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(ClientInfo::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::process-id\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_process_id_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    fn connect_type_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_type_trampoline<P: IsA<ClientInfo>, F: Fn(&P) + 'static>(
            this: *mut ffi::ALSASeqClientInfo,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(ClientInfo::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::type\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_type_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    fn connect_use_filter_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_use_filter_trampoline<
            P: IsA<ClientInfo>,
            F: Fn(&P) + 'static,
        >(
            this: *mut ffi::ALSASeqClientInfo,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(ClientInfo::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::use-filter\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_use_filter_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }
}

impl fmt::Display for ClientInfo {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("ClientInfo")
    }
}
