// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use crate::QueueTimerCommon;
use glib::object::Cast;
use glib::object::IsA;
use glib::signal::connect_raw;
use glib::signal::SignalHandlerId;
use glib::translate::*;
use std::boxed::Box as Box_;
use std::fmt;
use std::mem::transmute;

glib::wrapper! {
    #[doc(alias = "ALSASeqQueueTimerAlsa")]
    pub struct QueueTimerAlsa(Object<ffi::ALSASeqQueueTimerAlsa, ffi::ALSASeqQueueTimerAlsaClass>) @implements QueueTimerCommon;

    match fn {
        type_ => || ffi::alsaseq_queue_timer_alsa_get_type(),
    }
}

impl QueueTimerAlsa {
    pub const NONE: Option<&'static QueueTimerAlsa> = None;

    #[doc(alias = "alsaseq_queue_timer_alsa_new")]
    pub fn new() -> QueueTimerAlsa {
        unsafe { from_glib_full(ffi::alsaseq_queue_timer_alsa_new()) }
    }
}

impl Default for QueueTimerAlsa {
    fn default() -> Self {
        Self::new()
    }
}

pub trait QueueTimerAlsaExt: 'static {
    #[doc(alias = "device-id")]
    fn device_id(&self) -> Option<alsatimer::DeviceId>;

    #[doc(alias = "device-id")]
    fn set_device_id(&self, device_id: Option<&alsatimer::DeviceId>);

    #[doc(alias = "resolution-ticks")]
    fn resolution_ticks(&self) -> u32;

    #[doc(alias = "resolution-ticks")]
    fn set_resolution_ticks(&self, resolution_ticks: u32);

    #[doc(alias = "device-id")]
    fn connect_device_id_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    #[doc(alias = "resolution-ticks")]
    fn connect_resolution_ticks_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;
}

impl<O: IsA<QueueTimerAlsa>> QueueTimerAlsaExt for O {
    fn device_id(&self) -> Option<alsatimer::DeviceId> {
        glib::ObjectExt::property(self.as_ref(), "device-id")
    }

    fn set_device_id(&self, device_id: Option<&alsatimer::DeviceId>) {
        glib::ObjectExt::set_property(self.as_ref(), "device-id", &device_id)
    }

    fn resolution_ticks(&self) -> u32 {
        glib::ObjectExt::property(self.as_ref(), "resolution-ticks")
    }

    fn set_resolution_ticks(&self, resolution_ticks: u32) {
        glib::ObjectExt::set_property(self.as_ref(), "resolution-ticks", &resolution_ticks)
    }

    fn connect_device_id_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_device_id_trampoline<
            P: IsA<QueueTimerAlsa>,
            F: Fn(&P) + 'static,
        >(
            this: *mut ffi::ALSASeqQueueTimerAlsa,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(QueueTimerAlsa::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::device-id\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_device_id_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    fn connect_resolution_ticks_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_resolution_ticks_trampoline<
            P: IsA<QueueTimerAlsa>,
            F: Fn(&P) + 'static,
        >(
            this: *mut ffi::ALSASeqQueueTimerAlsa,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(QueueTimerAlsa::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::resolution-ticks\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_resolution_ticks_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }
}

impl fmt::Display for QueueTimerAlsa {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("QueueTimerAlsa")
    }
}
