// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use crate::QueueTimerDataAlsa;
use crate::QueueTimerType;
use glib::object::Cast;
use glib::object::IsA;
use glib::signal::connect_raw;
use glib::signal::SignalHandlerId;
use glib::translate::*;
use std::boxed::Box as Box_;
use std::fmt;
use std::mem::transmute;

glib::wrapper! {
    #[doc(alias = "ALSASeqQueueTimer")]
    pub struct QueueTimer(Object<ffi::ALSASeqQueueTimer, ffi::ALSASeqQueueTimerClass>);

    match fn {
        type_ => || ffi::alsaseq_queue_timer_get_type(),
    }
}

impl QueueTimer {
    pub const NONE: Option<&'static QueueTimer> = None;

    #[doc(alias = "alsaseq_queue_timer_new")]
    pub fn new() -> QueueTimer {
        unsafe { from_glib_full(ffi::alsaseq_queue_timer_new()) }
    }
}

impl Default for QueueTimer {
    fn default() -> Self {
        Self::new()
    }
}

pub trait QueueTimerExt: 'static {
    #[doc(alias = "alsaseq_queue_timer_set_alsa_data")]
    fn set_alsa_data(&self, data: &QueueTimerDataAlsa);

    #[doc(alias = "queue-id")]
    fn queue_id(&self) -> u8;

    #[doc(alias = "type")]
    fn type_(&self) -> QueueTimerType;

    #[doc(alias = "queue-id")]
    fn connect_queue_id_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    #[doc(alias = "type")]
    fn connect_type_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;
}

impl<O: IsA<QueueTimer>> QueueTimerExt for O {
    fn set_alsa_data(&self, data: &QueueTimerDataAlsa) {
        unsafe {
            ffi::alsaseq_queue_timer_set_alsa_data(
                self.as_ref().to_glib_none().0,
                data.to_glib_none().0,
            );
        }
    }

    fn queue_id(&self) -> u8 {
        glib::ObjectExt::property(self.as_ref(), "queue-id")
    }

    fn type_(&self) -> QueueTimerType {
        glib::ObjectExt::property(self.as_ref(), "type")
    }

    fn connect_queue_id_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_queue_id_trampoline<P: IsA<QueueTimer>, F: Fn(&P) + 'static>(
            this: *mut ffi::ALSASeqQueueTimer,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(QueueTimer::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::queue-id\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_queue_id_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    fn connect_type_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_type_trampoline<P: IsA<QueueTimer>, F: Fn(&P) + 'static>(
            this: *mut ffi::ALSASeqQueueTimer,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(QueueTimer::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::type\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_type_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }
}

impl fmt::Display for QueueTimer {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("QueueTimer")
    }
}
